/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoJoinJoinCodeRouteImport } from './routes/demo.join.$joinCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoJoinJoinCodeRoute = DemoJoinJoinCodeRouteImport.update({
  id: '/demo/join/$joinCode',
  path: '/demo/join/$joinCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/join/$joinCode': typeof DemoJoinJoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/join/$joinCode': typeof DemoJoinJoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/join/$joinCode': typeof DemoJoinJoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/join/$joinCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/join/$joinCode'
  id: '__root__' | '/' | '/demo/join/$joinCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoJoinJoinCodeRoute: typeof DemoJoinJoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/join/$joinCode': {
      id: '/demo/join/$joinCode'
      path: '/demo/join/$joinCode'
      fullPath: '/demo/join/$joinCode'
      preLoaderRoute: typeof DemoJoinJoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoJoinJoinCodeRoute: DemoJoinJoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
